import { listTriggers } from './manager.ts';

export async function installGitHooks(repoPath: string): Promise<string[]> {
  const installed: string[] = [];
  const triggers = listTriggers().filter(
    (t) => t.enabled && t.source === 'git_hook' && t.gitHook?.repoPath === repoPath,
  );

  for (const trigger of triggers) {
    if (!trigger.gitHook) continue;

    for (const hookName of trigger.gitHook.hooks) {
      const hookPath = `${repoPath}/hooks/${hookName}`;

      const script = `#!/bin/sh
# Cortex git hook: ${trigger.name}
# Generated by Cortex on $(date -Iseconds)

HOOK_NAME="${hookName}"
REPO_PATH="${repoPath}"

# Build JSON payload
PAYLOAD=$(cat <<EOF
{
  "event": "${hookName}",
  "repo": "${repoPath}",
  "timestamp": "$(date -Iseconds)",
  "branch": "$(git -C "${repoPath}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)",
  "commit": "$(git -C "${repoPath}" rev-parse HEAD 2>/dev/null || echo unknown)",
  "message": "$(git -C "${repoPath}" log -1 --format=%s 2>/dev/null || echo unknown)"
}
EOF
)

curl -s -X POST "http://localhost:3000/api/webhooks/${trigger.name}" \\
  -H "Content-Type: application/json" \\
  -H "X-Event-Type: git-${hookName}" \\
  -d "$PAYLOAD"

exit 0
`;

      try {
        await Deno.writeTextFile(hookPath, script);
        await Deno.chmod(hookPath, 0o755);
        installed.push(hookName);
        console.log(`[triggers:git] Installed ${hookName} hook for ${trigger.name} at ${hookPath}`);
      } catch (e) {
        console.error(`[triggers:git] Failed to install ${hookName} hook: ${(e as Error).message}`);
      }
    }
  }

  return installed;
}

export async function uninstallGitHooks(repoPath: string): Promise<string[]> {
  const removed: string[] = [];
  const triggers = listTriggers().filter(
    (t) => t.source === 'git_hook' && t.gitHook?.repoPath === repoPath,
  );

  for (const trigger of triggers) {
    if (!trigger.gitHook) continue;

    for (const hookName of trigger.gitHook.hooks) {
      const hookPath = `${repoPath}/hooks/${hookName}`;
      try {
        const content = await Deno.readTextFile(hookPath);
        if (content.includes('# Cortex git hook:')) {
          await Deno.remove(hookPath);
          removed.push(hookName);
        }
      } catch {
        // file doesn't exist
      }
    }
  }

  return removed;
}
